### ISSUE TITLE
不支持ios12？

### ISSUE THREAD

**Issue by leekyy** [cuiyu8580/ELWeChat#3]
不支持ios12？

**Comment by cuiyu8580** [comment]
我测试的时候是iOS11，但应该iOS 12也是可以的

**Comment by leekyy** [comment]
发件人: cuiyu8580 <notifications@github.com>
答复: cuiyu8580/ELWeChat <reply@reply.github.com>
日期: 2018年10月23日 星期二 16:13
收件人: cuiyu8580/ELWeChat <ELWeChat@noreply.github.com>
抄送: Leek <lsj8380880@hotmail.com>, Author <author@noreply.github.com>
主题: Re: [cuiyu8580/ELWeChat] 不支持ios12？ (#3)


感谢您的回复
我是用xcode和imazing 安装的。都说ios12不能安装。有可能是我的操作有问题。


我测试的时候是iOS11，但应该iOS 12也是可以的
